name: Pull Request Conventions

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [master, v*]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
          scopes: |
            deps
          requireScope: false
          # Configure additional validation for the subject based on a regex.
          # Ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          # When using "Squash and merge" on a PR with only one commit, GitHub
          # will suggest using that commit message instead of the PR title for the
          # merge commit, and it's easy to commit this by mistake. Enable this option
          # to also validate the commit message for one commit PRs.
          validateSingleCommit: true
